apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dashboard-redirector
  labels:
    app: dashboard
    tier: redirect
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "25%"
      maxSurge: 1
  selector:
    matchLabels:
      app: dashboard
      tier: redirect
  template:
    metadata:
      name: redirect
      labels:
        app: dashboard
        tier: redirect
    spec:
      containers:
        - name: rails-server
          image: g5search/heroku-moved:v1.0.0
          ports:
            - name: http
              containerPort: 9292
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "200m"
          env:
            - name: MOVED_TO
              value: "smart.g5marketingcloud.com"
            - name: REAL_REDIRECT
              value: "shallow"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9292
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 60
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9292
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 60
            failureThreshold: 4
